[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.bench]
debug = true

[dependencies]
simple_lines = "0.0.1"
itertools = "0.10.1"
thiserror = "1"
pathfinding = "3.0.5"